#!/bin/bash

# This helper script reads a file with assembly IDs, downloads the corresponding genomes and dereplicates them using skDER.
# The assembly IDs (file names generated by skDER) are then written to a file 'dereplicated_assemblies.txt'.
# So essentially: assemblies.txt -> dereplicated_assemblies.txt

echo The helper bash script has been initiated!

echo Preparing to download and dereplicate genomes...

#If intermediary/output files and folders exist, they need to be deleted:
if [ -f "../../data/output/cleaned_binary.csv" ]; then
    rm ../../data/output/cleaned_binary.csv
fi

if [ -f "../../data/output/clusters.txt" ]; then
    rm ../../data/output/clusters.txt
fi

if [ -d "../../data/genomes/all" ]; then
    rm -r ../../data/genomes/all
fi 

if [ -d "../../data/skder_out" ]; then
    rm -r ../../data/skder_out
fi

# Set some useful variables:
assembly_count=$(cat assemblies.txt | wc -w)  # Amount of words corresponds to amount of assembly IDs.
batch_count=$(cat assemblies.txt | wc -l)  # Each line is one batch. Enforced by the python script.

# The first argument is the ani-cutoff for skDER:
pi_cutoff=$1

echo Got $assembly_count assembly IDs. Downloading genomes in $batch_count batches...
 
# Create the directory to store all genomes
mkdir ../../data/genomes/all

# Here we loop over each line in the 'assemblies.txt' file:
while read line; do
    # Removing files that are autmoatically donwnloaded by NCBI datasets. 
    # This way datasets does not stop midway to ask the user if ti can override the files.
    if [ -d "../../data/genomes/ncbi_dataset" ]; then
        rm -r ../../data/genomes/ncbi_dataset
    fi

    if [ -f "../../data/genomes/md5sum.txt" ]; then
        rm ../../data/genomes/md5sum.txt
    fi
    
    if [ -f "../../data/genomes/README.md" ]; then
        rm ../../data/genomes/README.md
    fi 

    # Download the dehydrated genome package. xargs removes the trailing whitespace:
    datasets download genome accession $(echo "$line" | xargs) --dehydrated

    # Unzip the file in a folder called "genomes". This folder is located two steps up in the data folder
    unzip -d ../../data/genomes ncbi_dataset.zip

    # Rehydrate:
    datasets rehydrate --directory ../../data/genomes

    # Put all genomes from this batch into one directory
    mv ../../data/genomes/ncbi_dataset/data/GC*/* ../../data/genomes/all
done < assemblies.txt

echo Downloading finished!

# Print amount of files in the /genomes/all/ folder. This should equal the initial amount of assembly IDs
echo $(ls ../../data/genomes/all | wc -w) genomes in /data/genomes/all.
echo Directory size: $(du --human-readable -s ../../data/genomes/all).  # Size of the genomes folder

echo Dereplicating genomes with percent identity cutoff of $pi_cutoff.

# Run skDER on the downloaded genomes:
skder -g ../../data/genomes/all/* -o ../../data/skder_out -i $pi_cutoff

# skDER stores the dereplicated genomes in its own output folder. Compare the amount of files in skder_out folder with initial folder where 
# all genomes reside.
echo Dereplication done! $(ls ../../data/genomes/all | wc -w) genomes were converted into $(ls ../../data/skder_out/Dereplicated_Representative_Genomes | wc -w) genomes. 

# Now we have to write the accession numbers of the dereplicated genomes to a file:
ls ../../data/skder_out/Dereplicated_Representative_Genomes > ../../data/output/dereplicated_assemblies.txt

# CLEAN UP:
rm ncbi_dataset.zip assemblies.txt 
